name: Build and Scan
on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t my-image:latest .

    - name: Scan Docker Image with Trivy
      run: trivy image --format json -o trivy-report.json my-image:latest

    - name: Upload Trivy Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy-report.json
